### ISSUE TITLE
ActiveRecord setup for minitest-parallel_fork

### ISSUE THREAD

**Issue by bbozo** [jeremyevans/minitest-parallel_fork#2]
If you are interested to add it to the docs, and if not it'll be on google :) this is a setup I use in a Rails app: https://gist.github.com/bbozo/7a46abc4c04a9541cf7c4934d89182c1

Also, just to let you know I'm a huge fan and user of a bunch of your work, thank you for all that you did, it's some amazing stuff <3 if you go through Zagreb, there'll be a spare room for ya ^_^

Take care :)

**Comment by jeremyevans** [comment]
I think it would be useful to include that information for users who use ActiveRecord.  I'll try to add it to the README shortly.  Thanks!
