### ISSUE TITLE
marshal data too short (ArgumentError) 

### ISSUE THREAD

**Issue by pnomolos** [jeremyevans/minitest-parallel_fork#6]
I occasionally get this exception when executing my code on a CI server, but it seems to be sporadic at best, and I've never been able to reproduce on a local machine, so I'm not even sure where to begin debugging it.  The offending line is:

```
minitest-parallel_fork-1.1.2/lib/minitest/parallel_fork.rb:81:in `load': marshal data too short (ArgumentError) 
```

This has happened on both Travis and AWS CodeBuild, so it's not something specific to a CI, although it *may* be due to being run in a container.

I wasn't thinking and re-ran the build without grabbing the full trace, so unfortunately that's all that I have at the moment.

**Comment by jeremyevans** [comment]
Thank you for the report.  Unfortunately, with the limited information provided, there is not much I can do to troubleshoot.  The most likely scenario is a child process died or closed the pipe to the parent program without writing the information the parent process expects.  I suppose we could try to work around that and treat the `marshal data too short` as a general error (so the process does not exit with a 0 return status).  However, that may hide the actual issue and make troubleshooting more difficult.

**Comment by pnomolos** [comment]
@jeremyevans Any chance a specific debugging hook could be inserted on that failure so I could do stuff like grab logs and maybe figure out what's going on?

**Comment by jeremyevans** [comment]
I'd be open to that.  Would it be enough to have a block that is called when that failure occurs?  There's not much debugging information at that point, only the String with the marshalled data (which is probably empty).

**Comment by pnomolos** [comment]
Yes that would be perfect.  Since this is running in a container as root I can use that to grab any system-level logs and dump them in an S3 bucket.  Hopefully that will shed some more light on my situation.

**Comment by jeremyevans** [comment]
I've added a `on_parallel_fork_marshal_failure` in c0f2e1f83c04c3ff6424a97f64ddcead9efb634d.  Please try it out and let me know if it works for you.  If so, I can release a new version with it.
