### ISSUE TITLE
New gem release

### ISSUE THREAD

**Issue by larskanis** [jeremyevans/minitest-parallel_fork#7]
The latest release `minitest-parallel_fork-1.1.2` doesn't contain the callback as described in the README:

```ruby
Minitest.on_parallel_fork_marshal_failure do
end
```

@jeremyevans  Could you please make a new release to make it easily available?

**Comment by jeremyevans** [comment]
Definitely.  Sorry I didn't do this sooner, looks like it has been almost 2 years since that was committed.  I'll try to get the release out later today.

**Comment by jeremyevans** [comment]
Looks like there some issues with newer versions of minitest.  Fixing those issues now.

**Comment by jeremyevans** [comment]
Fixed those issues and released version 1.2.0.  Thanks again for the reminder.

**Comment by larskanis** [comment]
Thank you for maintaining this gem! I came across the incompatibility to Minitest-5.14+ as well, but was blocked by a [ruby-core issue](https://bugs.ruby-lang.org/issues/18077) with `Marshal.dump` before submitting a PR. The Marshal bug affects this gem and can be worked around by catching TypeError and IOError. But I think it's seldom enough to keep the code how it is.
